###################  项目启动端口  ###################
server:
  port: 8085

###################  spring配置  ###################
spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:~/camunda5
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456

  #    schema: classpath:db/schema.sql
  #    data: classpath:db/data.sql
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true

#logging:
#  level.root: info
#  level.com.haiyang: debug
#  path: logs/
#  file: flowable-test.log
#
#
#---
#logging:
#  level.root: warn
#  path: logs/
#  file: flowable-test.log

camunda.bpm:
  admin-user:
    id: admin
    password: admin
    firstName: Kermit
  filter:
    create: All tasks
